- name: configuring mysql component
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: start and enable mysql
    tags:
    - import
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1        